sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  - docker build -t lunohod1/multi-client ./client
  - docker build -t lunohod1/multi-nginx ./nginx
  - docker build -t lunohod1/multi-server ./server
  - docker buuid -t lunohod1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lunohod1/multi-client
  - docker push lunohod1/multi-nginx
  - docker push lunohod1/multi-server
  - docker push lunohod1/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-201262878045
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY